[package]
name = "vut"
version = "0.1.1"
authors = ["Kjartan F. Kvamme <forbjok@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib/lib.rs"

# CLI tool binary
[[bin]]
name = "vut"
path = "src/cli/main.rs"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[dependencies]
chrono = "0.4.10"
encoding = "0.2.33"
fern = "0.6.0"
globset = "0.4.4"
lazy_static = "1.4.0"
log = "0.4.8"
regex = "1.4.2"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = { version = "1.0.48", features = ["preserve_order"] }
structopt = "0.3.9"
strum = "0.19.5"
strum_macros = "0.19.4"
toml = "0.5.6"
toml_edit = "0.2.0"
walkdir = "2.3.1"
