[package]
name = "vut"
version = "0.1.0"
authors = ["Kjartan F. Kvamme <forbjok@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
fern = "0.5.9"
lazy_static = "1.4.0"
log = "0.4.8"
regex = "1.3.4"
serde = "1.0.104"
serde_json = "1.0.47"
structopt = "0.3.9"
strum = "0.17.1"
strum_macros = "0.17.1"
