[profile.release]
codegen-units = 1
lto = true
opt-level = "z"

[workspace]
resolver = "2"

members = [
  "cli",
  "lib",
]

[workspace.dependencies]
clap = "3.2.17"
encoding = "0.2.33"
globset = "0.4.9"
once_cell = "1.13.1"
regex = "1.6.0"
serde = "1.0.143"
serde_derive = "1.0.143"
serde_json = "1.0.83"
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.32"
toml_edit = "0.14.4"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
walkdir = "2.3.2"
