[general]
ignore = "**/.git"

[authoritative-version-source]
type = "cargo"
path = "lib"

[file-updaters.nuspec]
type = "regex"
replacers = [
  { regexes = "(<version>)(.*)(</version>)" },
]

[file-updaters."ChocolateyInstall.ps1"]
type = "regex"
replacers = [
  { regexes = "(\\$version = ')(.*)(')" },
]

[[update-version-sources]]
globs = "**"

[[update-files]]
globs = "**/*.nuspec"
updater = "nuspec"

[[update-files]]
globs = "chocolatey/tools/ChocolateyInstall.ps1"
updater = "ChocolateyInstall.ps1"
