[general]
ignore = "**/.git"

[authoritative-version-source]
type = "cargo"
path = "lib"

[file-updaters.nuspec]
type = "regex"
replacers = [
  { regexes = "(<version>)(.*)(</version>)" },
]

[[update-version-sources]]
globs = "**"

[[update-files]]
globs = "**/*.nuspec"
updater = "nuspec"
