[package]
name = "vut-cli"
version = "0.1.2"
authors = ["Kjartan F. Kvamme <forbjok@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "vut"
path = "src/main.rs"

[dependencies]
chrono = "0.4.19"
fern = "0.6.0"
log = "0.4.14"
serde_json = { version = "1.0.68", features = ["preserve_order"] }
structopt = "0.3.25"
vut = { path = "../lib" }
