[general]
  # Directories to ignore completely along with all their content.
  # Typically used to avoid wasting time on scanning VCS directories.
  ignore = [
    # Ignore Git directories
    "**/.git",
  ]

# Define version source pattern.
# There can be more than one of these.
[[version_source]]
  pattern = "**"

  # Uncomment if you want to exclude one or more patterns that would otherwise be included.
  #exclude_pattern = "some_dir/**"

  # Specify which source types to update.
  # By default, all source types will be updated.
  #types = ["vut", "cargo", "npm"]

# Define template pattern.
# There can be more than one of these.
[[template]]
  pattern = "**/*.vutemplate"

  # Directory to start scanning from.
  # If not specified, the root directory will be used.
  #start_path = "."

  # Directory to use as the root for output files.
  # If specified, this will cause output files to be generated in this directory,
  # in the template's subdirectory relative to the start path
  # instead of in the same directory as the template.
  # This should generally only be used if for some reason templates cannot exist
  # within a particular directory, as it makes it less obvious where files will be generated.
  #output_path = "."

  # Template processor to use.
  # The default, and currently only supported processor is "vut".
  #processor = "vut"

  # Encoding to use for these templates.
  # The default is "utf-8".
  #encoding = "utf-8"
