name: CI

on:
  push:
    branches: [ github-actions-test ]
  pull_request:
    branches: [ github-actions-test ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - stable
        - nightly
        - windows-msvc-x86
        - windows-msvc-x86_64

        include:
        - build: stable
          os: ubuntu-latest
          rust: stable

        - build: nightly
          os: ubuntu-latest
          rust: nightly

        - build: windows-msvc-x86
          os: windows-latest
          rust: stable
          target: i686-pc-windows-msvc

        - build: windows-msvc-x86_64
          os: windows-latest
          rust: stable
          target: x86_64-pc-windows-msvc

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Upload artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.build }}
        path: target/${{ matrix.target }}/release/vut.exe
