name: Release

on:
  release:
    types:
      - published

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: i686-pc-windows-msvc
        profile: minimal
        override: true

    - name: Build
      shell: pwsh
      run: .\build.ps1

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "dist/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
